/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dimen_ffmpegplayer_VideoPlayer */

#ifndef _Included_com_dimen_ffmpegplayer_VideoPlayer
#define _Included_com_dimen_ffmpegplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dimen_ffmpegplayer_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_dimen_ffmpegplayer_VideoPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_dimen_ffmpegplayer_VideoPlayer
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dimen_ffmpegplayer_VideoPlayer_sound
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dimen_ffmpegplayer_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dimen_ffmpegplayer_VideoPlayer_play
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
